hamlet-io/executor-bash

- cli/createTemplate.sh
Remove any deployment file that is not generated as part of the current processing.
Include the generation contract in the checking for changes, as it may do more than simply generate output files. This will mean that the switch from genplan to generation contract will trigger a redeployment of **ALL** units.
Restore the behaviour where a missing unit is treated as successful. A missing unit is detected if the generation contract is empty.
Currently files that were previously generated for a unit but that are now no longer generated will not be removed from the output directory. The immediate example is the switch from a genplan to a generation contract (https://github.com/hamlet-io/engine/pull/1240).
There was also a phase where replace1 and replace2 alternatives were generated for all …
> <refactor> Improve generation cleanup logic

- automation/jenkins/aws/manageBuildReferences.sh
- automation/jenkins/aws/manageDocker.sh
- automation/jenkins/aws/manageRdssnapshot.sh
- automation/jenkins/aws/manageS3Registry.sh
- automation/jenkins/aws/promoteRelease.sh
- automation/setContext.sh
Correct a syntax error in acceptance processing when managing build references.
Correct the exception handling when processing various types of build references.
Include the segment (if not default) in the tag used to obtain build references to use in the promotion process.
Testing of scoped registries and multi-segment solutions highlighted a few bugs in the support for release acceptance and promotion.
Tested with customer needing to use scoped registries and multi-segment solutions.
> <fix> Accept/promote processing

- automation/jenkins/aws/manageRepo.sh
Add up to 6 attempts to rebase a repo if the push fails to allow for the situation of heavy parallel load on the Jenkins server.
When working on multiple environments for a single product, it is possible for a repo to be updated between being rebased and pushed. To mitigate this, add retries and a delay between each retry.
> <refactor> Make CMDB commit logic more robust

- automation/jenkins/aws/buildJS.sh
Current logic will match a build target that contains but doesn't exactly match the required task. For instance a required task of `spa` will match a target of `build:spa`.
The commit ensures that anything other than an exact match will be ignored.
Current logic incorrectly attempts to invoke missing targets.
Customer site
> fix: Make build target matching more precise

- cli/manageDeployment.sh
- Fix issue loading utility.sh from plugin providers.
- Only attempt to deploy an ARM template if one exists.
Because the GENERATION_PLUGIN_DIRS environmental variable is a delimited list, it has to be split and looped over in order to find files to load, rather than passed as a complete filepath.
As for the Template deployment fix, this currently fails should a deployment unit rely solely on non-ARM template files such as purely bash scripts.
Local testing and resource deployment.
> Fix - Manage Deployment Utility Loader + Template if Present

- cli/runExpoAppPublish.sh
Some minor fixes and enhancements to the expo publish script 
- cleanup osx keychains if they have been created
- remove progress reporting for s3 actions as they fill log messages 
- add support for different node package managers - support npm lock files
- Update expo and turtle versions to the latest currently available  - mostly too keep up with what's available and ensure we support the latest sdks 
Some quality of life improvements having used this script for a number of different app builds
Will test off this PR
> feat(expo): clean keychains and node pkg support

- execution/freemarker.sh
Incorporate fix to wrapper into engine.
Wrapper was not correctly handling the CMDB file system. The CMDB file system is not currently used but is being upgraded in readiness for dynamic loading of the CMDB.
Local deployments.
> fix: Wrapper fix for CMDB file system

- cli/runExpoAppPublish.sh
Minor fix in expo build process to pick node package manager
switch statement was wrong which skipped the install process
tested locally
> fix(expo): node package manager lookup

- cli/runTask.sh
- Adds support for running fargate tasks using runTask 
- refactors configuration overrides based on blueprint into a json based input to allow for complex configuration objects which we can manage in jq 
Allows for running tasks without any ec2 instances deployed and instead uses fargate tasks 
Tested locally on active deployment
- [] Depends on https://github.com/hamlet-io/engine-plugin-aws/pull/44
> feature(task): fargate support for ecs tasks

- cli/manageDeployment.sh
- execution/common.sh
Moved the load of plugin providers utility.sh files into common.sh so its avail on both generation and deployment.
Should be available to both.
Local template generation and deployment.
> Fix - Plugin Utility.sh Move

- cli/runTask.sh
Adds support for supplying multiple environment variable overrides when running an ecs based tasks. 
Allow for someone to override as many of the environment variables they need to 
Tested locally on live deployment
> feat(task): support multiple env var overrides

- cli/runExpoAppPublish.sh
- Add support for bare workflow configurations.
- Add support for app extensions which have their own Info.plist files, bundle ids etc.
- Use the APP_REFERENCE, if present, to define the ShortVersionString. This needs to be set in app extensions to the same value as the app bundle.
- Ensure metro bundler not running before attempting a build, and stop it after the build is finished
SDK37 deprecated the use of Expokit in favour of the bare workflow.
Use of push notifications using onesignal service introduced the need to support app extensions.
Customer build
> feat: Bare workflow support for Expo builds

- execution/utility.sh
Executor support for https://github.com/hamlet-io/engine-plugin-aws/pull/64 
Uses the AWS cli to apply the VPN gateway options. Waits for each VPN connection to be updated before moving on to the next one
Allows for fine grain config of VPN gateways which aren't available in cloud formation
Tested locally
> feat(aws): cli task for vpn options

- execution/utility.sh
If a filename starts with the pattern `encoded--.+--`, assume it has been pre-encoded so when copying it to S3, set the necessary metadata to serve it correctly.
The initial use case for this is to provide compression in cloudfront for files greater than 10Mb, which cloudfront won't dynamically compress.
A lambda@edge function can detect the prefix in the requested URL and change the origin URL to target the pre-encoded file.
Local deployment to a test S3 bucket
> feat: Add content encoding metadata

- automation/constructTree.sh
Add more robust checking for account and product directories to allow for the possibility of them sharing the same name e.g. product=environment or account=product.
Because the logic supports the pre and post v2.0 cmdb formats, also a range of cmdb granularities, its possible there are still configurations were the new logic will fail, but we will deal with them when they happen. For now, this will address the common examples identified above.
Support for configurations using shared names for accounts/product/environments/segments
> fix: Shared account/product/environment/segment names

- cli/manageCrypto.sh
- execution/utility.sh
Make the handling of options for crypto operations more robust in terms of valid combinations.
Increase the level of checking before encoding metadata is applied when copying s3 files.
- Less chance of incorrectly handling crypto operations
- More robust application of encoding metadata to s3 objects
> refactor: More robust crypto options and s3 syncing

- automation/jenkins/aws/setCredentials.sh
Further fixes for the azure login using service principal
Didn't test locally, rookie mistake,
Tested locally this time
> fix(azure): login method using service principal

- cli/createTemplate.sh
Prevent cleanup of existing files when mocking content.
Current testing process requires for testcase.json files all in the same directory (directory depth of 1 - see output of `hamlet test generate --help`). So when running unit tests, all files are output into the same directory, compiled, then run together. Cleaning up the output directory as we go ends up deleting all but the last set of files.
Local testcase generation, compilation and execution in the Azure provider.
> Fix - Test Case File Cleanup

- execution/setContext.sh
Remove unnecessary brackets.
Brackets were half-deleted from a prior pr.
Local testing.
> Fix Iffy Conditional

- automation/jenkins/aws/manageRepo.sh
- execution/utility.sh
This PR aligns log levels with the standard ones for log4j2.
Log level support is being added to the engine core, log4j2 is used for that purpose. In order to have it aligned with the executor logs, trace level should be lower than debug.
> fix(logging): align log levels with log4j2

- cli/runExpoAppPublish.sh
Adds an option to set the source of the app bundle version, either CMDB or from the expo app manifest file 
Expo apps by default have versioning as part of their manifest structure. This is used by developers to specify if a new binary file needs to be produced and this version source has been used across a number of our apps. Making the source controllable allows for both version structures, CMDB I.e. app reference and the manifest file
Tested locally
> fix: allow setting version source for expo builds

- cli/runExpoAppPublish.sh
Typo fix for version source case
Broken 
Tested locally
> fix(expo): version source case statement

- cli/manageCrypto.sh
If saving decrypted content, it also needs decoding applied.
Decrypting files is resulting in correct content.
Local execution.
> fix: Decoding on decryption

- cli/createTemplate.sh
- execution/freemarker.sh
Align the logging of the wrapper with the general log level being applied during generation.
Console logs are more understandable if debug information is not displayed unless requested.
Local generation runs.
> feat: Freemarker log level control

- cli/createTemplate.sh
The bash execution implementation of https://github.com/hamlet-io/engine/pull/1362 
Currently uses the level provided to set the deployment group for backwards compatibility 
To provide blueprint based control on deployment group and unit discovery 
Tested locally
> Deployment groups

- cli/createTemplate.sh
- execution/contextTree.sh
Adds the "schema" template pass and appropriate subset types
```sh
$GENERATION_DIR/createTemplate.sh -l schema -u component
```
* Note - if you are within a specific providers solution directory, you may need to provide provider/framework flags
```sh
$GENERATION_DIR/createTemplate.sh -l schema -u component -p azure -f arm
```
hamlet-io/docs#5
hamlet-io/engine#1364
Local template generation alongside corresponding Engine PR
> feat(schema): new template level - schema

- cli/createTemplate.sh
Adds a template assignment for the `schema` level of createTemplate.
Missing mandatory attribute for template generation on the schema level.
Local template generation.
> Fix - Schema Generation

- execution/utility.sh
Add WAF logging configuration utility
Currently not supported by AWS CloudFormation
- Core - https://github.com/hamlet-io/engine/pull/1366
- AWS - https://github.com/hamlet-io/engine-plugin-aws/pull/105
- Bash Executor -  https://github.com/hamlet-io/executor-bash/pull/71
> feat: add waf logging utility

- cli/runLambda.sh
Some minor fixes to make the run lambda script work with its default parameters
The script doesn't appear to have been working at all, running it would result in a exit with a non 0 exit code and no reason why
Tested locally
> fix(run): lambda run not running with params

- cli/createTemplate.sh
Allows for the generation of management contracts as outlined in https://github.com/hamlet-io/engine/pull/1381
This allows for create template to support the management contract subset 
Tested locally
> feat: support mgmt contract generation

- execution/utility.sh
closes: https://github.com/hamlet-io/engine-plugin-aws/issues/123
minor changes based on testing 
- put-account-setting only defines the setting for the principal running the command, to make it more obvious where configuration comes from this has been removed 
- Remove any principal level configuration of settings that hamlet is controlling - This ensures that the hamlet default settings a followed for deployments using this principal 
- Show the effective setting for the principal which is running the command as this cannot be determined from the aws console 
Make the ecs settings more understandable given the hot mess they already are. 
> fix(ecs): display effective value for validation of settings

- execution/utility.sh
Remove hardcoded region from utility script
It should use the provided region to support any region
Tested locally
> fix(ecs): minor fix to use provided region

- cli/manageStack.sh
In order that the stack is available for subsequent stack processing, save the current stack when a change set reports a failure.
Change sets report a status of "Failed" if there are no changes to perform.
This is currently detected and a warning shown, but the current stack is not saved.
Customer installation
> fix: Capture stack when change set fails

- cli/runTask.sh
- Fixes an issue with handling a failed task startup 
- Adds a retry count for watching the task status, ensures we don't get stuck in infinite loops from the while loop
When a task failed to be started by ECS it wasn't quite handling the error properly and didn't return a reason why to the user
There have been cases where a task status check gets stuck and as a result of the while loop used to check status it would get stuck in an infinite loop. We can't watch a task forever but sometimes they do take some time. So we fail our job and provide the information to the user
Tested locally
> fix(ecs): handle failed task start and provide timeout for checks

- automation/setContext.sh
If APPLY_TO_ALL_DEPLOYMENT_UNITS is set to true, use the same git commit for all provided units.
The use of stream jobs triggered from tags of code repos means that all the information related to which unit was built from what repo is effectively quarantined in the code repo Jenkinsfile.
The same commit/tag then needs to be applied to the build references of all provided units. The APPLY_TO_ALL_DEPLOYMENT_UNITS setting does this for tags, but if the commit is not set, the mapping between units and code repos still needs to be known when managing build references.
To avoid the need to configure this information via the existing `*_CODE_REPO` settings, extend the function of the APPLY_TO_ALL_DEPLOYMENT_UNITS setting to also apply any git commit found to all provided units. The existing …
> feat: Force all units to same commit

- execution/utility.sh
Add rebase retries in case of repo access conflicts.
Also correct an issue with content hub handling where a directory change was not temporary.
Contenthub updates were failing because of update conflicts when multiple jobs were triggered at the same time.
The directory handling was causing epilogue scripts to fail as they expect to be in the unit directory of the state subtree.
> fix: push repo utility

- execution/utility.sh
Correct a syntax error on the tries parameter.
Failing deploys.
> fix: utility push

- cli/createTemplate.sh
- execution/contextTree.sh
- execution/setContext.sh
- execution/utility.sh
Additional cache changes to allow for cache creation outside of createTEmplate
setContext is called outside of createTemplate 
Tested locally
> Fix cache creation

- cli/manageCrypto.sh
Minor fix to include the level in build blueprint look ups to support recent changes to the unit processing
With the recent changes to introduce the entrance the build blueprint now supports and requires the level and unit of a deployment unit. This ensures that we lookup the correct unit
Tested locally
> fix: update blueprint file name for key

- execution/setStackContext.sh
The definition file uses a fixed level so reflect this in the naming.
This file variable is now being used by the api gateway whereas previously it was likely unused given the naming was incorrect.
> fix: explicitly set level for definition file

- automation/jenkins/aws/buildDataSetS3.sh
- automation/jenkins/aws/buildRDSSnapshot.sh
- cli/manageCrypto.sh
- cli/runExpoAppPublish.sh
- cli/runLambda.sh
- cli/runSentryRelease.sh
- cli/runTask.sh
Fixes/Refactors executor run tasks which rely on output from blueprint generation 
With the changes implemented in #105 the filenaming for blueprint files has been handed over to the engine to control. As a result of this the file name outputs have changed sightly. This PR resolves this and also sets a standard way to manage the generation of the blueprint files 
Tested locally
> refactor: align template generation with output changes

- cli/createTemplate.sh
Add the ability to pass arbitrary parameters to an entrance.
Reorganise script structure to reflect the required nature of entrances/flows.
Entrances can have quite disparate parameter needs. This PR adds the ability to pass arbitrary parameters to an entrance, with the intention a wrapper script will validate and collect these for use by the generate template script. The entrance can then validate that the specific parameters it needs have been provided.
The approach of wrapper scripts is already in use for blueprints and buildBlueprints.
Local builds
> feat: custom entrance parameters

- cli/createTemplate.sh
Use the correct variable to pass entrance parameters to pass processing.
Use separate variables for the list and array equivalent of variables.
Entrance parameters were not being passed through to processing.
> fix: custom entrance parameters

- execution/utility.sh
Add utility routines to format the message of a git commit according to the conventional commit (https://www.conventionalcommits.org/).
Add support for local directory control to the git utility routines.
Split the formatting of the git url from the other routines which use it.
Permit the working directory to not be within the repo.
This PR lays the groundwork for removing the use of tags to record the execution of process steps in favour of more complete use of commits. It will also permit the replacement of manageRepo.sh with more direct git control in scripts via the utility routines.
Local testing
> feat: add conventional commit formatting

- automation/jenkins/aws/manageBuildReferences.sh
- automation/jenkins/aws/manageImages.sh
- automation/jenkins/aws/manageRepo.sh
- automation/jenkins/aws/promoteRelease.sh
- cli/manageCredentialCrypto.sh
- cli/runExpoAppPublish.sh
- execution/freemarker.sh
- execution/manageJSON.sh
- execution/utility.sh
* Refactor the `fatalMandatory()` bash function, providing specific errors as to which variable was required but missing. 
* set a tidy value for the `PS4` environment variable, allowing bash to output an erroring calling functions features
```bash
$ return_on_invalid_environment_variables 255 "ENV_VAR" "ENV_VAR2"
(Fatal)Mandatory argument missing: ENV_VAR. Check usage via -h option.
(Fatal)Mandatory argument missing: ENV_VAR2. Check usage via -h option.
exit_on_invalid_environment_variables "GENERATION_DIR" "NOT_REAL"
/home/hamlet/cmdb/hamlet/executor/cli
bash: !i: Undefined mandatory environment variable: NOT_REAL
```
Current error messages for fatalMandatory provide little advice as to what variable is missing. This is compounded by nested bash scripts using the argument.
Local …
> Refactor - FatalMandatory Function

- execution/utility.sh
Use the CFN output lookup process to determine the ARN for the WAF log destination instead of getting it from the stack outputs 
This removes the need for double passes or other complicated methods 
Tested locally
> refactor(waflogs): lookup ARN from cfn output

- execution/utility.sh
Utility function to implement implement https://github.com/hamlet-io/engine/pull/1456 
The function is intended to be run as a pregeneration script for components which support external image loading via URL it includes build reference generation, and image upload to the registry
This allows for portability for components across tenants, products and environments as the image doesn't need to be built and locked to a specific segment/build
tested locally
> feat(utility): pull image from external source for registry

- execution/utility.sh
Align the variables checked for content to the signature of the functions.
The handling of parameter checking was recent changed. Looks like two PRs got out of synch resulting in the wrong set of parameters being checked.
Client deployment
> fix: correct checked environment variables

- cli/runExpoAppPublish.sh
Various fixes to the expo publish process 
- Update expo and turtle cli minimums to the latest versions 
- removes QR code generation - this feature hasn't been used and with the move to expo native builds this is no longer usable 
- Uses the home brew link process to ensure the correct latest version of fastlane is being used 
- Adds LANG settings based on latest fastlane version requirements 
- Attempts uploads of binaries to both platforms and shows warnings instead of failing if one doesn't work 
Various fixes as part of keeping up with the latest expo build and publish process
Tested on deployed server
> Expo Publish - Various fixes

- execution/utility.sh
updates the image sourcing from Url script to handle files which aren't zip files. When this happens the hash of the URL image is still used but before uploading the file into the registry the file is zipped up so that we can treat it like our standard image registry files.
This is useful when you only have to provide one file and removes the need to zip it up which can seem a bit weird when you have a single file or want to source it directly from a public example
Tested locally
> feat: non zip image url sourcing

- execution/freemarker.sh
Write methods, logging level control and various bug fixes.
Lay the foundation for moving cmdb upgrades into the engine.
Requires https://github.com/hamlet-io/engine/pull/1530
> feat: wrapper upgrade to 1.12.1

- cli/createTemplate.sh
Provide a starting set of layers to the engine
This will start the process of transitioning to dynamic cmdb loading and controlling which district is required via profiles etc rather than what is in the blueprint.
> feat: starting layers

- execution/freemarker.sh
Pick up fixes to the wrapper related to write functions.
Precursor to moving migration functions into the engine.
Depends on https://github.com/hamlet-io/engine/pull/1542
Local testing
> fix: freemarker wrapper write functions

- automation/jenkins/aws/manageRepo.sh
Since [CMDB tagging has been removed](#129), the fix for push when a repo HEAD is detached became needed.
When CMDB tagging was removed, deploy jobs for higher environments stopped updating the stack outputs in CMDBs. This doesn't prevent the releases from being successful but doesn't allow to track the history of stack updates in CMDBs.
In addition, I made the script always fail if the push wasn't successful.
A modified piece of the script was tested locally.
> fix: add a check for detached head

- execution/freemarker.sh
This version introduces additional search options and addresses and number of housekeeping tasks.
See https://github.com/hamlet-io/engine/pull/1553 for details
> feat: switch to v1.12.3 of the wrapper

- README.md
Overhaul the repository README
Consistency across the Hamlet Deploy ecosystem (content was very old)
n/a
> docs: overhaul of the README

- cli/createTemplate.sh
Adds support for the entrance added in https://github.com/hamlet-io/engine/pull/1578 
Handles output naming for the occurrences entrance 
Tested locally
> feat: add occurrences entrance support

- cli/runTask.sh
Look for the task name in the SubComponent structure. 
This is now needed due to a fix for https://github.com/hamlet-io/engine/issues/1584.
Local execution.
> fix: runtask lookup of subcomponent

- cli/createTemplate.sh
Sort object attributes prior to json file comparisons.
With the changes to output generation, all previously generated json files will show differences because of the indeterminant nature of object attributes.
To avoid this, sort keys as part of the comparison of json files. Semantically the files are the same even if syntactically they are
different.
Local template generations
> refactor: sort json objects for comparisons

- cli/setup.sh
Set the input that causes errors associated with missing plugins to be ignored.
With the introduction of input pipelines, the way to ignore errors for missing plugins has changed.
Local script invocation
> fix: setup entrance parameters

- execution/freemarker.sh
Uses the latest engine wrapper for executor calls
Uses the latest features of the wrapper for the engine to use 
-  Requires: https://github.com/hamlet-io/engine/pull/1643
> feat: move to using the latest freemarker wrapper

- cli/createTemplate.sh
removes logging of engine results from the executor and into the hamlet engine. This separates the responsibility between the engine and the executor
Implementation of https://github.com/hamlet-io/engine/issues/1635
Tested locally
> refactor: engine logging support for bash

- cli/createTemplate.sh
Do the generation log file checks first in case the result is empty.
The generation log and the result file are always separate now.
- None
> fix: reorder template error checks

- cli/createTemplate.sh
- Removes engine exception processing from the executor and relies on the engine to provide exception details
- Adds basic log messages on exceptions to show some context around exceptions raised by the engine
- Removes inline log message detection as this is handled in the engine
Aligns with https://github.com/hamlet-io/engine/pull/1645 
This change extends the separation between the bash executor and the engine and allows for the engine to manage its own exceptions
Tested locally
- Requires: https://github.com/hamlet-io/engine/pull/1645
> refactor: move exception handling to engine

- cli/createTemplate.sh
- execution/utility.sh
- updates createTemplate to provide a generation contract stage to the engine during template generation
- updates the script to then handle multiple output validation for each process_template_pass invocation
- fixes https://github.com/hamlet-io/executor-bash/issues/185 
Generating multiple outputs at a time reduces duplication of the setup processes required in the engine. Part of https://github.com/hamlet-io/engine/issues/1666 
Initial testing shows some improvements in performance 
```
time hamlet -i mock -p aws -p awstest deploy test-deployments
```
```
multipass
real    9m38.630s
user    11m33.315s
sys     2m16.764s
```
```
single pass
real    13m2.916s
user    15m29.790s
sys …
```
> refactor: support multipass executions

- cli/createTemplate.sh
updates the handling of missing generation contracts when using multipass generation stages
If a generation contract was not found the script would continue like it had one which caused failures
- None
- None
- None
> fix: handling for missing generation contract

- .dockerignore
- .github/workflows/package.yaml
- .github/workflows/package.yml
- Dockerfile
Adds support for creating a base package for the hamlet executor
Implementation of https://github.com/hamlet-io/architectural-decision-log/issues/11 to allow for distributing hamlet using docker based images/layers
Will be tested as part of this PR
- None
- None
- None
> feat: docker based packaging

- cli/manageStack.sh
- Adds event reporting for stack processing failures
- Adds change set support to create events to show what resources would be created by a new stack
- Adds resumption support when the script fails and an operation is still in progress on the next run of manageStack
- Reduces the log output to only provide required information as needed
- Refactors the progress reporting to show status markers on a single line to reduce log space
- Only update the stack output file in the CMDB when an update has completed
- reduce default wait to provide more feedback to updates now that the value …
> feat: stack management processing

- cli/manageStack.sh
- fixes an issue where replace stacks were being ignored and not
processed
- fixes some of the return handling to ensure failures stop processing
as soon as possible
Replace  templates were no longer being applied when they were expected to be
Tested locally on active deployment
- None
- None
- None
> fix: replace templates in manage stack

- execution/utility.sh
- Adds support for setting the Reference property of build refs which allows for custom build units to be defined
- Removes the settings reassembly from the update build reference function. This allows it to be used in other contexts
This update allows for the update_build_reference function to be used in other contexts like adaptors that pull images for other components 
https://github.com/hamlet-io/engine/pull/1713
- None
- None
- None
> refactor: remove assemble settings from image pull

- .github/workflows/changelog.yml
- .github/workflows/package.yml
- .gitignore
Updates the pipelines to align with testing and operational usage
- Make the changelog PR a draft and mark the unreleased changes as
latest. This allows us to tag the release with a change log and not have
to move it
- Add support for writing build details into the source
Make CI process consistent and easier 
Tested on aws repo
- None
- None
- None
> refactor(ci): updates from testing and ops

- .github/workflows/changelog.yml
- .github/workflows/package.yml
Change `main` branch references to `master`
Likely cut/paste error
Test once PR committed
- None
- None
- None
> fix: master branch references

- automation/constructTree.sh
- automation/jenkins/aws/integrator/constructTree.sh
- execution/freemarker.sh
- removes startup, patterns and generation cloning from construct tree as this is now handled by the cli and bootstrap processes
- Allows for the java freemarker wrapper file path to be specified through an environment variable
Support for https://github.com/hamlet-io/architectural-decision-log/issues/11 which allows the wrapper to be treated as its own engine source/part. 
Removes processes that are no longer required
Tested locally
- None
- None
- None
> refactor: engine install process updates

- execution/freemarker.sh
Update to the latest version - 1.15.1
Pick up changes needed for cmdb migration.
- https://github.com/hamlet-io/engine/pull/1719
- None
- None
> refactor: wrapper upgrade to 1.15.1

- execution/freemarker.sh
renames the wrapper environment variable to align with the format used for the other engine environment variables
Aligns the naming of environment variables used to reference different engine parts 
- None
- None
- None
> refactor: align wrapper env with engine envs

- .dockerignore
adds the .git directory to the docker ignore list to reduce the size of the container
reduce the size of the container images used to build the engine. Build information is included under the .hamlet dir
tested locally
- None
- None
- None
> refactor(ci): remove git dir from docker images

- cli/manageStack.sh
Removes the check for the stack file existing if no changes have been made
ensures that the stack file is always present and fixes #238 
- None
- None
- None
> fix: always update stack if no changes are found

- .github/workflows/package.yml
minor fix to update tagging for docker image tagging
Aligns with the standard tagging structure used for docker images
Tested on other repos
- None
- None
- None
> fix: tagging update for docker images

- cli/runSentryRelease.sh
updates the sentry source maps to align with the required file naming for react-native based apps
Make source maps work for react-native apps
Will be tested with active pipeline
- None
- None
- None
> feat: handle react native bundle files in sentry

- .github/workflows/release.yml
Handle releases and packaging when dealing with tags
create a consistent build process 
- None
- None
- None
> feat(ci): handle tag based releases

- cli/runSentryRelease.sh
- uses an explicit prefix strip instead of stripping the common prefix as it doesn't appear to be reliable 
- Adds a validation step to ensure that the sourcemaps are what they expect to be 
Source maps not working reliably 
Will be tested with PR branch
- None
- None
- None
> fix(sentry): strip explicit prefix and validate

- cli/createTemplate.sh
- execution/setContext.sh
- Updates deployment directory checking to only run when a deployment group is provided
- fixes an issue where locations for layers not in the solution weren't being discovered
- sets the account based on current location if variable isn't set
Allows for using some of the broader entrances available within the engine against account level deployments or other layers 
Tested locally
- None
- None
- None
> refactor: account level deployment discovery

- execution/setCredentialsSource.sh
- adds checking for a provided role when using ENV or USER role
- extends the error message to make it easier to understand how to configure auth
- configures the mfa token if provided on both the source and assumedrole profiles
This change allows for running hamlet deployments within a single account or using credentials issued from the account you want to deployed into. 
Tested locally
- None
- None
- None
> feat: add support for deploying into local account

- cli/runExpoAppPublish.sh
syntax error fix ups for publish script
script was failing to run 
- None
- None
- None
> fix: typo in app publish script

- execution/utility.sh
This was to fix https://github.com/hamlet-io/engine-plugin-aws/issues/254
Locally
- None
- None
- None
> feat: handle waf logging disable on delete

- automation/constructTree.sh
When using an existing tree in automation commands use the current directory structure to determine the current district the user expects to work from
This allows for the automation commands to run in a similar process as the generation commands which are consolidated within the hamlet python cli. 
Tested locally
- None
- None
- None
> feat: set district on location in automation

- execution/utility.sh
- Adds a conversion step to retrieve the ssh-key public key from the private key when uploading to aws.
- Adds handling for generating non standard ssh keys on baseline components
With recent updates to the keys supported by AWS for ssh key-pairs it appears that they no loner support public keys provided as pem files and instead require ssh formatted public key files
tested locally 
- None
- None
- None
> fix(sshkey): convert to sshkey pair for upload

- .github/workflows/changelog.yml
- generate the latest change log when tags are pushed
Ensures the changelog that is merged after a release aligns with the release tags
- None
- None
- None
> fix(ci): generate changelog on tag

- automation/jenkins/aws/manageRepo.sh
Always format the provided repo message as a conventional commit instead of just for standard commits
Easier handling of commit message formatting
- None
- None
- None
> refactor: always format commit message

- execution/utility.sh
- updates output for tunnel ip lookups to support parsing into arrays
Allows for easier processing of the ips in scripts
Tested locally
- None
- None
- None
> fix(aws): make tunnel ip support bash arrays

- execution/utility.sh
Correct the parameter substitution into the utility routine to set the active ruleset for SES at the account level
Bugfix
Replay of Jenkinsfiles
- None
- None
- None
> fix: set ses active ruleset parameter substitution

- automation/jenkins/aws/manageRepo.sh
- changes the remote check command so that if an error occurs the git details are returned to the user instead of a replaced generic error
Makes it easier to troubleshoot issues with git remotes and to understand why they have failed
Tested locally
- None
- None
- None
> refactor: show output on failed remote check

- execution/setCredentialsSource.sh
- Aligns the naming of the azure auth configuration with what is used for AWS
The newer configuration options didn't quite align with what was being used in AWS
- None
- None
- None
> fix: align azure auth envs with aws envs

- cli/createTemplate.sh
- Remove subdirectories for runbook based entrances
Adds support for new entrances which don't need to be saved under placement directories
Tested locally
https://github.com/hamlet-io/engine/pull/1900
- None
- None
- None
> feat: output handling for runbook entrances

- cli/runSentryRelease.sh
- Replaces AUTOMATION_DATA_DIR with temp dir or WORK_DIR explicit config
- Determines the AWS region from the placement of the mobileapp
Moving to using the CLI and some of the context provided through older automation context configuration is no longer available. This replaces those parts with other implementations.
Tested locally
- None
- None
- None
> fix: sentry release cli support

- execution/freemarker.sh
- adds explicit control over using a jar file or bundled wrapper
- Adds checks and error to make sure file is available
Makes it more obvious and controllable over the wrapper that is being used
Tested locally
- None
- None
- None
> refactor: handling of bundled vs jar wrapper

- execution/setContext.sh
- use the right syntax for location case discovery
- Add default to segment for the district
Template generation failing when run from another district 
- None
- None
- None
> fix: district default handling

- automation/common.sh
- automation/jenkins/aws/manageBuildReferences.sh
- automation/jenkins/aws/manageDocker.sh
- automation/jenkins/aws/manageRepo.sh
- automation/jenkins/aws/manageS3Registry.sh
- cli/createTemplate.sh
- cli/manageDeployment.sh
- cli/manageStack.sh
- execution/common.sh
- execution/utility.sh
- Adds an event log which tracks commands that update the cmdb or make changes to deployed state
- Updates CMDB save actions to check the log for events that match the directories in the cmdb and pull them from the log
- Adds logging events across hamlet commands to track usage
- refactor manageBuildReferences to align with updated code formats
- Allows for spaces in messages that will be saved to the body of commit messages 
This allows for more detailed tracking of events that occur during hamlet commands in both the automation and generation side of things. As the log events are created at the point of the event occurring, if …
> feat: event logging tracking

- cli/createTemplate.sh
- makes sure that the imagedetails entrance doesn't have a sub dir
Support for imagedetail queries
- None
- None
- None
> feat: add entrance output dir for imagedetails

- cli/createTemplate.sh
When saving a template, sort object attributes alphabetically. This assists when manually analysing the templates by making attributes easier to locate.
This should have no effect on existing deployments as key sorting is already part of the comparison process.
- None
- None
- None
> refactor: sort template objects

- automation/jenkins/aws/constructTree.sh
- execution/utility.sh
Correct the extraction of the caller for the deprecated script warning.
Add sourcing of common scripts to the automation tree construction script in order to correctly display the deprecation warning.
- assist deprecation warning in being as helpful as possible
Local script execution
- None
- None
- None
> fix: script deprecation warning

- cli/runExpoAppPublish.sh
- Allows for providing google_services files as overrides in cmdb
- Adds notes on the package that provides xq
- Fixes KMS decrypt process of files found in the ops path
- fixes ls error that didn't need to be there
google_services.json files are used to define the keys and client ids used for access to google based services for andoird apps include firebase push notifications. Allowing for overrides of this file supports isolating these files from the code repo as they can provide access to production services 
tested locally
- None
- None
- None
> feat(expo): support for google services file overrides

- cli/runExpoAppPublish.sh
- info plist update requires project details to work
Expo script was failing
tested locally
- None
- None
- None
> fix(expo): include project details for plist

- automation/jenkins/aws/manageRepo.sh
- execution/utility.sh
- remove redundant code
- add support for deferred push
- broaden regex for values in name/value pairs to handle spaces in fields such as the description.
- permit commit descriptions and messages with spaces
- add implementation of deferred push
Local commits.
- None
- None
- None
> fix: conventional commit support

- cli/runExpoAppPublish.sh
- Reduce the number of command line options available to simplify the script and the build process
- remove the setup command to allow for users to define how they want there env setup.
- Add dependencies check instead of setup command
The bash script itself had too many options that were required to be setup instead of providing configuration through the cmdb 
Removing the env setup supports users picking how there env is setup.
- None
- None
- None
> refactor(expo): reduce command line options

- cli/runExpoAppPublish.sh
- Update the expo script to align with testing results
- Locks expo global cli to v5* to keep support for existing SDKs
Fixes from testing the process across multiple apps
Tested locally
- None
- None
- None
> fix(expo): testing updates for expo publish

- cli/runSentryRelease.sh
In addition to renaming bundle files update of sourceMappingURL was added to align with the new filenames. 
The correct value in sourceMappingURL is needed for the correct stacktrace frames to be shown in Sentry. 
Locally
- None
- None
- None
> fix: update sourceMappingURL value after bundle rename

- .github/workflows/changelog.yml
- .github/workflows/release.yml
- Disable changelog generation on tags
- Use a reusable workflow for image building
Makes it easier to manage and standardise the release process
- None
- None
- None
> cd: update workflows to shared workflows

- execution/utility.sh
- Aligns changes to the aws image management with the scripts
- Removes build reference updates for pulling images from external locations
- Add support docker pulls for providing digest refs instead of tag refs
Aligns the bash executor with the changes in https://github.com/hamlet-io/engine-plugin-aws/pull/658 
Tested locally
- None
- None
- None
> feat(image): Update scripts for image support

- .github/workflows/release.yml
Now that testing has confirmed the workflow is working lock the version that is used
- None
- None
- None
> refactor: lock version for image release

- execution/utility.sh
- removes the cli commands required to enable logging in v1
See https://github.com/hamlet-io/engine/pull/2090
Tested locally
- None
- None
- None
> refactor(waf): remove older waf logging setup

- automation/jenkins/aws/manageRepo.sh
Revise the return code handling to ensure errors during pushes are correctly reported. In the process, streamline return code handling overall and remove use of the EXIT trap handler which made the code more complex without adding much value.
Save failures were going undetected as a result of branch protection changes.
Tricky to do in isolation - simplest to do visual review and then respond quickly to any observed issues.
- None
- None
- None
> fix: repo management return code handling

- .github/workflows/changelog.yml
- .github/workflows/release.yml
Updates the shared github workflows used to the latest version
Resolves a bug in the changelog generation and moves to using the latest nodeJS version in the actions
- None
- None
- None
> chore: update github actions pipelines

- cli/createTemplate.sh
- Provide the cf_dir to the engine so that it can be included in deployment contracts
- None
- None
- None
> feat: add cf_dir to engine
