hamlet-io/executor-bash

automation/jenkins/aws/buildSetup.sh, automation/jenkins/aws/manageBuildReferences.sh, automation/setContext.sh
Add support for registry scope on each deployment unit in any of the other deployment activities such as prepare and promote.
setContext now includes registry scope as a fourth parameter on a build reference, and an array of registry scopes is included in the context file that passes context between steps.
manageBuildReferences expects the registry scope array as with the other build reference arrays, so each build unit can have its own scope value.
The initial support for scoped registries only supported the build/CD phase of deployment.
Tested with the site currently needing the support.
=> <fix> Registry scoping support for prepare/promote

cli/createTemplate.sh
Combine the submessages re updating and removing files.
Ensure that lastchange files are not cleaned up - they are treated the same as stacks.
Cleaning up is only done when differences are detected so combine all the cleanup messages under a single heading.
Lastchange files are related to stack processing not template processing so treat the same as stacks i.e. don't delete.
Locally ran template creation and confirmed that 
- the output messages were as expected
- the lastchange.json file was not removed.
=> <refactor> Simplify output cleanup logging

.github/PULL_REQUEST_TEMPLATE.md
- Add a refactor option as a type of change.
- Add a none of the above item to the checklist.
As a significant number of the PRs generated fall into this category, it feels sensible to add this as an option. The alternative is to call them features which doesn't quite feel right.
The extra checklist item is to confirm that the submitter has reviewed the checklist but not found any relevant items.
Example in https://github.com/hamlet-io/executor-bash/pull/4
=> <refactor> Add additional options to PR template

cli/manageDeployment.sh
Addresses and Closes #12 - updating Az CLI commands from the deprecated ones to the latest ones.
Deprecation warnings during all deployments warning us that eventually these commands would stop working.
Updated locally and performed a deployment - no warnings.
=> updated commands from deprecated to recommended

automation/jenkins/aws/manageS3Registry.sh
Removes progress logging from s3 registry management scripts
When copying large registries the log messages overwhelm the rest of the job logs. Removing the progress log entries still maintains the list of files copied in the log, it doesn't include the percentage progress.
Tested in releases of active deployment
=> <refactor> remove progress log entries on s3 registry

cli/createTemplate.sh, execution/setContext.sh
With the splitting of fragment assembly across setContext.sh and createTemplate.sh, `TEMPLATE_COMPOSITES` needs to be exported so that it is available to a later invocation of createTemplate.sh.
Needed to correct execution logic for expo builds.
Customer build
=> fix: Fragment processing

execution/utility.sh
Ensures passwords are reset during the deployment rather than being scheduled for the next maintenance window in RDS updates
It appear that Aurora clusters in AWS RDS environments by default schedule password resets for the next maintenance windows rather than applying them immediately. This means that with our current password  configuration process on each deployment the password will be reset to a dummy value and wont be set to the correct value until the next window. 
Tested on live deployment
=> fix(db): ensure db password resets are performed when required

cli/createTemplate.sh
Composite lists were not being included when cacheing was enabled.
Simplify the logic by removing a redundant environment variable used to pass the path to each composite file.
Cacheing wasn't usable as builds failed without the composite fragment.
=> fix: Fragment handling when composite cacheing enabled

cli/manageCrypto.sh, cli/manageFileCrypto.sh
Add the ability to re-encrypt existing ciphertext. This makes creating new segments much easier where files or attributes need to have the same plaintext values. Instead of having to obtain the plaintext, existing ciphertext can be copied and then re-encrypted.
The re-encrypt command also provides the original key id as an output, so this has been used to provide the ability to list the cmk used to encrypt any ciphertext. The resulting value is then used to query what alias the key has.
Simplify the management of encrypted configuration
Local cmdb updates
=> feat: Re-encrypt and list cmk crypto operations

execution/utility.sh
Adds a lookup for the TransitGateway attachment when using a VPN connection. 
Required for: https://github.com/hamlet-io/engine-plugin-aws/pull/48 
The VPNConnection Cloudformation resource is used to attach to a TransitGateway, as a result of this the Transit Gateway attachment Id isn't available from Cloudformation. The attachment Id is required for routing configuration and propogation config 
This is covered as a request to the CFN team in https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/308 
Tested locally
=> feat(externalnetwork): vpn attachment lookup

cli/manageDeployment.sh
Export a second temporary directory variable for usage in scripts, as per is present in other shell scripts.
Both `${tmpdir}` and `${tmp_dir}` are supported elsewhere, and the absence of one will cause inconsistent script behaviour.
Local template deployment via manageDeployment.sh
=> fix(manageDeployment): tmpdir and tmp_dir to be equal

execution/contextTree.sh, execution/utility.sh
Adds support for Ec2 volume encryption by default
- A utility to support controlling the state of the encryption 
- Additional account level units to support the required services
AWS have introduced a regional level setting which enables encryption on EBS volumes by default. This saves having to enable it on a disk by disk basis. 
=> feat(ec2): volume encryption

execution/utility.sh
Companion PR to hamlet-io/engine#1343 
With the move to use Cloudformation for creating the SSM Session manager document we no longer need to create documents via the Cli. 
However we do need to be able to clean up the documents created outside of CFN, so instead we need a cleanup function
To support the changes in hamlet-io/engine#1343 
=> feat(console): replace ssm document creation with cleanup

automation/jenkins/aws/manageUnits.sh, automation/jenkins/aws/setCredentials.sh, cli/manageDeployment.sh, execution/setContext.sh, execution/setStackContext.sh
Adds support for managing azure logins and setting the active subscription 
- Allows for specifying the authentication source as managed-identity, interactive or service-principal. These can be set by environment variables with the default action as interactive 
- uses the existing stack name generation to set a default resource group. Also checks what the current resource group name is to support the current resource group override
This is to support running templates from a automated process and to align with the similar behaviour we for the the AWS execution
Tested locally with both aws and azure deployment
=> feat(azure): Support for credentials and consistent stack naming

automation/jenkins/aws/setCredentials.sh
Cleanup azure credentials lookup, should just have two levels, account specific and tenant
When this was originally setup it followed the AWS standard a bit to much which has an extra layer to lookup username from AWS keys which isn't in Azure
Tested locally
=> fix: azure credentials lookup

automation/jenkins/aws/manageUnits.sh, automation/setContext.sh
Some minor fixes in manageUnit to use environment variables available during the automation phases ( AZID wouldn't be there as this is a generation side variable ) 
Deployments would get the right credentials but used the wrong deployment script
Tested locally
=> fix(azure): use provider to set manage command

cli/manageCrypto.sh
When listing the current CMK under which ciphertext is encrypted, ensure a reasonable set of values are set for key other input parameters.
For this command, some other command line options need to be set to specific values for the command to complete successfully, so force these values regardless of what the user did or didn't provide.
Local testing
=> refactor: Reasonable defaults for CMK listing

automation/jenkins/aws/manageBuildReferences.sh
Check if the detail message already contains the unit detail to ensure it isn't added more than once.
This is mainly to support the Jenkinsfiles where the update build references and deploys are don in the same build, so currently the unit detail is included twice.
Customer deployments
=> refactor: Avoid duplicate unit listing

execution/contextTree.sh
Support the ability to upgrade a cmdb via setting the pinned version to the desired version.
Currently, the only way to force a cmdb version to a value greater than the framework default is by setting the GENERATION_MAX_CMDB_UPGRADE_VERSION variable. Adjusting the pinned value allows selective update of cmdbs.
=> feat: CMDB Upgrades via pinning

automation/setContext.sh
Fixes the environment account lookup when using segment level accounts
It wasn't working when only a segment level accounts were set
Tested on active deployment
=> fix: env lookup for segment account

cli/runExpoAppPublish.sh
Allow for the installation of a specific turtle version per publish run
The turtle cli only comes with bundler binaries for a fixed set of Expo SDK Versions. This causes issues with older expo versions as they can't be built
=> feat: allow per publish turtle install

cli/runExpoAppPublish.sh
Retry `pod install` with `--repo-update` if action was finished with error.
Expo publish with fastalane binary build may fail if pod repo needs to be updated. To fix it the parameter `try_repo_update_on_error` with value `true` has been added to the `fastlane run cocoapods` command.
On an OSx box within the expo publish job.
=> fix(expo): add try_repo_update_on_error to fastlane run cocoapods

cli/runExpoAppPublish.sh
Some expo clients seem to have issues with using the default assetOverrideUrl `./assets` as they try to use the `./` as a URL reference rather than resolving it to a relative URL 
This change sets the URL to an absolute value, since we know the absolute value anyway this makes it more explicit
Some expo clients were failing to update
Tested locally
=> fix: set assets url to an absolute value

cli/runExpoAppPublish.sh
Change assets path to a relative folder rather than the absolute url as expo can't seem to figure out the difference
Expo doesn't seem to be able to determine if a URL is absolute or relative
Will test with deployment
=> fix: assets path override

cli/runExpoAppPublish.sh
Updates the expo manifest file for fastlane builds to the explicit build format and SDK version based manifest file 
When specifying the manifest file in plist files for IOS the path to the manifest is to the actual manifest file rather than the directory containing the manifest like it is for the expo app.json 
TEsted locally
=> fix: set fastlane manifest URL to build format specific version

automation/jenkins/aws/setCredentials.sh, cli/manageDeployment.sh, execution/setContext.sh
Adds an AZ_AUTH_METHOD of none which skips the azure login process
This is mainly for local testing where you might not be able to access the azure account from the machine you are doing local testing on. When using the default interactive login the screen will lock until you proceed
Tested locally
=> feat(azure): disable login if cant access subscription

cli/runExpoAppPublish.sh
A collection of fixes in the expo publish process 
- Adds the major version of the app into the manifest location  on fastlane builds. This allows for breaking changes to be rolled out gradually ( introduce breaking changes in a new major app version, then as the binary is rolled out they will be come available ) 
- Only run the multi manfiest builds for turtle based builds  - the different SDK/multimanifest support only works with the expo client which only works with turtle 
- Remove QR codes from the fastlane builds as they don't work
To support safer deployment of apps built using expo and reduce the time to publish apps
Tested on an active deployment
- **NOTE** the move to a new OTA location means that new binaries will need to be distributed to receive the latest update
=> feat(expo): publish otas under app major version

execution/utility.sh
Removes the bash utility for service linked roles 
Now maintained using an account level cloudformation template
tested locally
=> refactor: replace script with cfn account template for service linked roles

execution/utility.sh
Adds a utility function to assign an appropriate security group to the filetransfer VPC Endpoint
Currently when the AWS Transfer VPC Endpoint is provisioned it defaults to using the default VPC Security group which doesn't allow inbound access to the service and can't be managed from Cloud formation. This utility swaps the default security group for a security group created by hamlet during the template deployment process
- executor-bash : https://github.com/hamlet-io/executor-bash/pull/76
- engine: https://github.com/hamlet-io/engine/pull/1369
- engine-plugin-aws: https://github.com/hamlet-io/engine-plugin-aws/pull/108
=> feat(filetransfer): security group management for filetransfer

cli/createTemplate.sh
include the fragment composite in unit list generation
We now include fragment processing in the state of external components, since the unit list needs the state of each deployment unit the fragment needs to be processed as part of finding the deployment units
Tested locally
=> fix: include fragment composite in unitlist generation

execution/setStackContext.sh
Add a check to ensure the find is not executed if the segment directory doesn't exist yet.
Currently find throws an error the first time a unit is deployed to a segment.
=> fix: State tree deployment unit directory detection

automation/jenkins/aws/manageUnits.sh, cli/manageDeployment.sh
Implements "Dry Run" and "Quiet" flags on the manageDeployment script used by the Azure provider. Dry Run provides the output of the Azure CLI "what-if" against a deployment, and in combination with the quiet flag, the output is also copied into a file for use with Hamlet Plans.
Closes #72 
Local template generation followed by testing with the `-q -y` flags. Also tested without them to ensure it wasn't impacted.
=> Enable Dry Run for Azure Provider

cli/createTemplate.sh
Detect the first time a template is created for a segment and always use deployment unit specific subdirectories.
Currently find throws an error when the first template for a segment is created, because the segment state dir doesn't exist.
=> fix: No error when missing segment state dir

execution/contextTree.sh, execution/utility.sh
bash executor implementation of https://github.com/hamlet-io/engine/pull/1393 
Provides a utility to control the ECS account settings, it applies both the default ( if a more specific principal doesn't have the setting configured ) and also performs an override to an principals that currently have the settings applied. This ensures consistency across the deployment process
Tested on local active deployment
- engine - https://github.com/hamlet-io/engine/pull/1393
- executor-bash - https://github.com/hamlet-io/executor-bash/pull/85
=> feat(aws): add support for ecs account settings

.gitignore, cli/createReference.sh, cli/createTemplate.sh
A collection of changes to support test generation with the mock input provider 
- Include the fragment file generation process as this is required to use the fragments which are part of the hamlet core code such as account fragments
- Support a cache dir that isn't part of the CMDB for mock input sources
- Add support for disabling the output cleanup process so that when using the OUTPUT_DIR parameter multiple deployment units can be staged in the same directory without being overridden 
- Don't enable deployment unit subdirectories when using the OUTPUT_DIR parameter 
- Cleanup output by removing dd status for run id generation
This PR adds a collection of cleanups and features to handle the generation of mock input templates which are used for our testing suite. Before management …
=> Testing Support fixes

execution/setContext.sh
Adds error handling that checks for an empty composite blueprint.
Currently, if your JSON somewhere in the Solution is malformed (such as a missing a bracket), the error that reports is that the Region is undefined (because it can't find it in the composite blueprint). This will first check to see if the file has any content at all, and provide more accurate advice as to the cause.
Local template generation.
=> Additional Error Handling

cli/manageStack.sh
Look for both CREATE_COMPLETE and UPDATE_COMPLETE when detecting if a stack completed successfully.
Currently the logic looks for a specific COMPLETE status. However, if a create stack is not saved for whatever reason, and the stack creation is repeated, hamlet will look for an UPDATE when the stack output will still say CREATE_COMPLETE (assuming no changes result from rerunning the template).
Customer Site
=> fix: More robust detection of stack completion

cli/manageStack.sh
Make the message unique for each instance where we treat a change set as successfully completed.
In order to make debugging easier.
=> fix: Make warnings unique

automation/jenkins/aws/manageDocker.sh, automation/jenkins/aws/manageRdssnapshot.sh, automation/jenkins/aws/manageS3Registry.sh
Add support for a build scope of "account". This permits the same build to be referenced across multiple segments/environments in an account. It replaces the product identifier with the fixed value "account".
Also support for a fixed value build scope. This permits all segments in a product to reference the same build.
The initial use case for account scope is for code units that are shared across multiple products in an account, such as lambda authorisers. 
For single product accounts, account and fixed scope achieve the same result. The choice is more to self-document the intention, i.e. across products (account) or within a product (fixed). A future extension would be to elevate account level to tenancy level, for enterprise wide functionality (lambda authorisers, virus scanning etc). …
=> feat: "account" and fixed build scope

automation/jenkins/aws/manageBuildReferences.sh, automation/jenkins/aws/validateUpdateBuildReferenceParameters.sh, automation/jenkins/aws/validateUpdateBuildReferencesParameters.sh, execution/contextTree.sh
Refactor the script based management of builds to permit the formats and scope for a build to be determined from a shared build file.
This will mean that build.json files only need to contain the commit and optional tag, and formats/scopes need only be defined once as part of the solution via the shared build directory tree.
The freemarker engine already supports this approach. A planned change is to move build updates to inside the freemarker engine so this logic is contained in one place.
Client deployment
=> refactor: scope/formats from shared build

automation/jenkins/aws/manageDocker.sh, automation/jenkins/aws/manageRdssnapshot.sh, automation/jenkins/aws/manageS3Registry.sh
Minor fix for #96 / #95  Which removes the scope from the registry path if it is either unset or unkown 
When the scope isn't know it is currently being included as a ? in the artefact path
Can't currently test this without deployment
=> fix: ignore registry scope if not set

execution/freemarker.sh
When an exception occurs in a template generation using the freemarker wrapper the process should exist with a non zero exit code so that other processes can report this failure.
A minor fix for  #77
Tested locally
=> fix: exit code for templates generation

automation/jenkins/aws/manageBuildReferences.sh
Check both build.json and shared_build.json for the scope and segment for a build.
Both files can be present in the shared build tree. As scope/segment refer to the build itself, it seems more logical to put those in a build.json file in the shared tree, while if the unit is actually shared, then a reference in a shared_build.json suggests the correct
semantic.
Once built, will be tested with customer site.
=> feat: Support shared build.json and shared_build.json in the shared build tree

automation/jenkins/aws/manageBuildReferences.sh
Checks for shared formats/scope should be performed even if no build file exists.
This covers the creation of the build reference where the check is still needed for shared formats/scopes..
=> fix: shared formats/scope checks

cli/createTemplate.sh, execution/common.sh, execution/contextTree.sh, execution/setContext.sh, execution/utility.sh
Allows users to configure the cache directory used to assemble composite files during template generation 
This also moves the default cache location to `${HOME}/.hamlet/cache` to guarantee that the location can be written to, if this isn't the case then `GENERATION_CACHE_DIR` can also be set 
Currently we use the `ROOT_DIR` of the CMDB that we are working in to define the location of the cache, with the introduction of the mock input source and the ability to create templates that do not depend on an underlying CMDB this directory is unreliable to use across all template passes 
So instead we need to have a writeable location that can be used to store the composite files. The users home drive feels like the safest location and allows for future usage if required
Tested locally
=> feat: make cache directory configurable

cli/createTemplate.sh
Minor fix on cache creation to ensure that the cache is available when its required. Uses the ROOT_DIR as the cache folder if its available
The cache dir was being created after it was required in template generation
Tested locally
=> fix: template cache creation directory

cli/runExpoAppPublish.sh
Minor fix to align build blueprint file name in expo with #105 
build blueprint not generated properly 
Tested locally
=> fix: expo build blueprint filename

cli/createBuildblueprint.sh
Add level support for build blueprint generation 
Previously the level was used as a override to generate the build blueprint with #63 the level/group now needs to be provided to ensure the right unit is selected
Tested locally
=> fix: build blueprint setup script

automation/jenkins/aws/integrator/setContext.sh, cli/createTemplate.sh, cli/runLambda.sh
Add detection of messages in templates starting with "Hamlet".
This is the first step in removing all usage of "COT" in favour of the current name. Once all usage has switched to "Hamlet", a second PR will be needed to remove the checking for "COT".
Once this PR is commited, the following PRs can then be merged;
=> refactor: switch COT to Hamlet

cli/createTemplate.sh, cli/runExpoAppPublish.sh
A collection of fixes to the expo build process 
- Allow for generation of templates even if you aren't in the SEGMENT dir instead we require that the SEGMENT_SOLUTION_DIR variable is defined. This achieves the same outcome but allows for the createTemplate command to be run anywhere
- Remove multi manfiest generation for turtle based expo builds as they are no longer supported and were not really used anyway 
- Add env var for turtle builds to provide the P12 IOS password
Expo/turtle based IOS builds were failing
Tested on OSX build server
=> Fix expo build

cli/createTemplate.sh
Separate out the formatting of the definition file into its own function.
Ensure consistency of filenames across uses.
=> refactor: separate function to get openapi definition

cli/createTemplate.sh, execution/utility.sh
Move get_openapi_definition_filename to utility.sh
The function needs to be available during manageStack as well as createTemplate.
=> refactor: definition filename function global

cli/runSentryRelease.sh
Minor fix to set temp dir variable so generation process saves a build blueprint file to the expected directory.
The sentry release script reads data from the config file, so we generate it as a part of the process. If a config file is not fond were it is expected to be the script fails. The variable which specifies the output directory needs to be set before generation of the config file.
locally
=> fix(sentry): set tmpdir variable

cli/manageDeployment.sh, cli/manageStack.sh, execution/setStackContext.sh
Allows for overriding the output directory location for manageDeployment and manageStack 
This is most likely a rare occurrence but the intention is to align the manageDeployment and manageStack commands with the createTemplate command which can specify a custom output directory 
Tested locally
=> feat: allow for overrides of outputdir in deployments

cli/manageStack.sh
Minor fix to include the OUTPUT_DIR in the getopts definition
It was included in documentation and case statement just not in the actual bit that uses it 
Tested locally
=> fix: include output dir in getopts

automation/jenkins/aws/acceptRelease.sh, automation/jenkins/aws/deploy.sh, automation/jenkins/aws/deployRelease.sh, automation/jenkins/aws/manageEnvironment.sh, automation/jenkins/aws/manageRepo.sh, automation/jenkins/aws/updateBuildReferences.sh, execution/utility.sh
The tagging of the cmdb to reflect automation activities has not proven of use so this PR removes it from the various points where it was previously performed.
Given that the same information as the tag is included in the cmdb commit message, the PR refactors it to be compliant with the
conventional commit standard, which makes it more usable. To minimise the change needed to achieve this, the commit message provided to manageRepo is assumed to be name/value pairs and key named values used to construct the conventional commit. Two extra named parameters are included to allow explicit control over the type and description.
It is difficult to test automation jobs without a Jenkins instance so the testing plan is to commit the changes, quickly test in key customers, and rapidly address any …
=> refactor: remove cmdb tagging

automation/constructTree.sh, automation/jenkins/aws/deploy.sh, automation/jenkins/aws/deployRelease.sh, automation/jenkins/aws/manageAccount.sh, automation/jenkins/aws/manageEnvironment.sh
In line with https://github.com/hamlet-io/executor-bash/pull/129, this change removes the tagging of changes made to the account cmdb.
Also add some further comments to automation jobs which are no longer committing/tagging the config part of the cmdb on the basis that they should only be affecting the infrastructure side, now that we are not tagging repos.
Consistent with the approach to product configuration references, it introduces an ACCOUNT_CONFIG_COMMIT to use as the configuration reference value when updating accounts.
The commit messages will also start being formatted as conventional commits, with the first account id as the scope.
The bulk of the changes to the formatting of commits have already been tested with PR129. The simplest way to test this is to rerun a manageAccounts …
=> refactor: remove tagging of accounts cmdb

cli/runExpoAppPublish.sh
Adds the android build tools into the setup installation
This allows the android packaging process to create architecture specific binary builds which can be used to create smaller packages
Tested locally
=> feat(expo): support abi builds in android

automation/setContext.sh
Ensure the git commit is captured in setContext.sh even if no deployment units are known initially.
A previous change (https://github.com/hamlet-io/executor-bash/pull/101) to ensure the git commit was applied to all units if
desired did not account for the situation of builds, where the deployment unit to be used is not known until later in the process, but the git commit needs to be captured early.
This commit detects that condition and captures the git commit.
Modified affected build to test the change.
=> fix: git commit for builds

execution/utility.sh
Adds an ec2 utility to remove scalein protection from any active instances in an autoscale group 
See https://github.com/hamlet-io/engine-plugin-aws/pull/192 for motivation
Tested locally and on active deployments
=> feat(ec2): support for disabling scale in protection

cli/createTemplate.sh
A minor fix to allow for fragments to to be empty in the hamlet engine.
This is required to support our migration to extensions which no longer
need to be assembled into a single template
Tested locally
=> fix: support empy engine fragments

execution/utility.sh
reverts the change added in https://github.com/hamlet-io/executor-bash/pull/136/commits/569a5f07e7e49bedbc85083fb5dc8fcb15c942c7 to allow for a list of space separated values to be provided to the aws cli for scale in protection
When providing a list of values to the aws cli it requires the values as space separated values ( https://docs.aws.amazon.com/cli/latest/reference/autoscaling/set-instance-protection.html ) 
the output from the command that we retrieve the values from returns a space separated list so we need to allow for word splitting when providing the value to the aws cli.
Tested locally
=> fix(ec2): allow for word splitting on instances

execution/utility.sh
Bash execution handling for https://github.com/hamlet-io/engine/pull/1495 
- Adds support for pulling and pushing a public docker image into our local ECR registry 
- Refactors the build reference update process to support different external sources 
Note: We don't fail builds if the docker service isn't responding, instead we show a warning. This is to handle local development which could be occurring a container which doesn't have access to a docker socker
This allows for docker images to be included in the hamlet deployment that haven't been built as part of the products ci/cd pipeline. This can include standard utilities or images built by other processes
Tested locally
=> feat(docker): support pulling images during generation

cli/createTemplate.sh, cli/setup.sh, execution/common.sh, execution/setContext.sh, execution/utility.sh
executor implementation of https://github.com/hamlet-io/engine/pull/1469 which implements plugin sourcing and configuration from a CMDB via a contract. 
The engine generates a loader contract which outlines the plugins which need to be loaded. Using this information the executor establishes a plugin cache and retrieves the plugins from their sources.
The cache allows for the plugins to be shared across different districts when working locally
The process also generates a state file which can be used to determine the version of the different hamlet plugins that were used for a given pass. If the setup script isn't used to load the plugins then the existing
processes will continue working
Also adds some utility routines to handle urls for git auth
The motivation behind this change is to …
=> feat: plugin loading from contract

execution/setContext.sh, execution/setStackContext.sh
Support the ability to override the region an account level unit is deployed into in the same manner as is currently supported for products.
Also correct use of unicode quotes by replacing with ASCII equivalent.
This has been introduced to support the ability to create account level SES configuration for receiving emails in the regions in which it is supported.
Local template generation.
=> feat: account deployment unit region override

execution/utility.sh
Minor fix to the Url image source function to use the correct variable for the build ref source 
Allows you to see where an artefact came from in a URL based image source
Tested locally
=> fix: correct var for source build ref

cli/createTemplate.sh
Refactor the createTemplate logging to remove new lines and to try and make the output more concise 
Difference 
**Existing** 
```
${GENERATION_DIR}/createTemplate.sh -l solution -u door-cdn 
(Info) Generating generationcontract file ...
(Info) No change in generationcontract detected ...
(Info) Generating documents from generation contract /tmp/cot_NsoXDB/create_template_1YNPwd/create_template_MvD7x1/results/soln-door-cdn-mswdev02-ap-southeast-2-generation-contract.json
(Info) Generating prologue file ...
(Info) Ignoring empty prologue file ...
(Info) Generating template file ...
(Info) No change in template detected ...
(Info) Generating epilogue file ...
(Info) No change in epilogue detected ...
(Info) Generating cli file ...
(Info) Ignoring empty cli file ...
(Info) No differences …
```
=> Refactor createTemplate logging

cli/setup.sh
Adds a check to see if the plugin folder with the a cloned repo exists as part of setup
This provides users with information about why their plugin might not be loading properly and also allows for pipeline state to still be populated when one plugin is missing. Since we check for the plugin loading during the engine we handle the missing plugin at that point 
Tested locally
=> refactor: handle missing plugin in setup

cli/createTemplate.sh
Adds support for the schemacontract output handling in createTemplate. 
By default we still allow entrance outputs to pass through the processing which by default sets a collection of file prefixes. The region and account are applicable for outputs generated outside of deployments so they should not be included in file name output
Tested locally
=> feat(createTemplate): schemacontract outputs

cli/runExpoAppPublish.sh
Allows for configuring the code sign identity for IOS builds
This allows support for the newer Apple Distribution certificates which replace the existing iPhone Distribution certificates
Will test on active deployment
=> fix(expo): control code sign id for ios

cli/runExpoAppPublish.sh
In recent versions of expo the sdkVersion filed has been removed from the app.json file and instead this information is sourced via the expo code using the package.json file if its required. 
This change removes the use of the sdkVersion and instead uses the  version flag set in the app.json or provided through hamlet as the APP_REFERENCE 
We use the sdkVersion to set revisions of the OTA locations to ensure that OTAs can be published to older apps if required. With the removal of the sdkVersion from the app.json we need to set a new location
=> Fix expo ota revision

cli/runExpoAppPublish.sh
Minor fix to correct the codesign variable usage in the expo script 
Script failing to run. The variable name went through a few itterations and wasn't corrected in all required places
Tested locally
=> fix(expo): codesign variable names

cli/createTemplate.sh, execution/utility.sh
- Set the root dir correctly when updating settings
- move definition update to only apply on api definition updates
- add force on docker prune to remove prompt
- When updating build reference in a hamlet environment with two products in different tenants the update was applied in the wrong location 
- definition update only applies to the api gateway, we now use pregeneration for other purposes 
- docker prune was waiting for a confirmation 
tested locally
=> fix: url image source updates

cli/createTemplate.sh
Ensure a value is provided to the `-g` switch of the freemarker wrapper where possible.
The cmdb migration support needs to know where to look for cmdbs, even if most processing of the cmdb has been disabled e.g. via the `-i mock` switch.
Local template testing
=> refactor: try and always populate cmdb root dir

cli/runExpoAppPublish.sh
Allows for providing encryption exemption status as part of the testflight submission process. This handles a manual step required on each upload to the Testflight store
Removes the need for testflight uploads to be held up by manual process
Will test on development environment
=> feat(expo): set encryption exemption on upload

cli/runExpoAppPublish.sh
Uses npx to force the installation of specific versions of the expo tooling ( expo-cli and turtle-cli ) at execution of the command. A cache dir is created on each build to hold a cache of the packages
For some reason npx ( which is intended to run the "closest" binary of an npm package) is using the global package and ignoring the one installed during the setup routine. This enforces it and essentially runs the same thing
Tested locallly
=> Force Expo tool versions

cli/createTemplate.sh, execution/setContext.sh
Supports the whatif input source. When the whatif input source is specified we should still assemble the composite CMDB like we normally do but require that outputs are sent to an external directory to avoid mock contaminating the composite CMDB
Allows for testing changes to a CMDB without requiring dependent deployments 
Tested locally
=> feat: whatif input source

automation/constructTree.sh, automation/jenkins/aws/manageAccount.sh
Adds support for setting the ref to to use for account cmdbs inline with the configuration available for product CMDBDs
During construct tree when cloning a repo which uses the main branch as the default branch the repo clone fails
Will be tested on deployment
=> feat(automation): add ref for account repos

cli/createTemplate.sh, execution/freemarker.sh
Refactor the template creation process to better capture and analyse the output of the freemarker wrapper. Also return specific return codes for `#stop` requests and for template processing errors.
By identifying these conditions, it is possible to integrate this with more general automation to report template generation failures as soon as they occur.
Local testing in conjunction with https://github.com/hamlet-io/engine/pull/1556
=> feat: engine status codes

cli/createTemplate.sh
Minor fix to remove the region and account details when generating diagram outputs
These attributes are not relevant for diagram details which focus on the overall solution
Tested locally
=> fix: diagram file output naming

execution/common.sh, execution/utility.sh
- Uses numeric function to determine the appropriate log level which allows for less or greater than and  equal to functions
- Sets the default log level to `info` to ensure a log level is always set
Aligns with the engine behaviour which uses equal to in comparison
Makes it easier to understand how the logging levels work and what they should do
Tested locally
=> refactor: log level comparison

execution/utility.sh
Adds bash util to find the IP Addresses for a VPN Connection for https://github.com/hamlet-io/engine-plugin-aws/pull/253
The IP address for the tunnels isn't available through cloudformation and its useful for monitoring the status of the tunnel
Tested locally
=> feat(util): aws vpn connection tunnel ip

cli/createTemplate.sh, cli/manageCrypto.sh, cli/manageDeployment.sh, cli/manageSSLCertificate.sh, cli/manageStack.sh, cli/rebootRDSDatabase.sh, cli/runExpoAppPublish.sh, cli/runLambda.sh, cli/runPipeline.sh, cli/runSentryRelease.sh, cli/runTask.sh, cli/snapshotRDSDatabase.sh, cli/updateObjectACL.sh, execution/setContext.sh, execution/setCredentials.sh
In the bash executor cli only get the credentials for cloud providers when they are required
With the use of more query tooling in the hamlet cli we generate templates which are used by a hamlet user to find out about thier deployment
Fixes #173 
Tested locally
=> refactor: only get credentials when required

cli/createTemplate.sh, execution/utility.sh
bash implementation updates for https://github.com/hamlet-io/engine/pull/1583
- Removes file naming from the executor and relies on the engine and the generation-contract to handle file naming 
- Removes the level attribute and replaces it with the deployment group property. This was partially complete and has now been completed
- Removes the ability to specify the DEPLOYMENT_UNIT_SUBSET in deployments. Recommendation is to use deployment groups and resource sets for this functionality 
- Makes the tmp output dir that is used during generation a CMDB ( includes a .cmdb file ) so that the engine can write to the tmp directory as it requires ( using the engine toCMDB methods ) 
- The file provided to the engine via the -o flag is now used to store the output generation log instead of …
=> feat: pass outputfilename from gen contract

cli/createTemplate.sh
A fix to createTemplate which stops file name strings from being evaluated for their content when running the freemarker wrapper 
Template generation where the file provided to the output_filename existed in the local directory and its contents were passed to the wrapper as the argument value
Tested locally
=> fix: createTemplate wrapper argument evaluation

README.md, automation/constructTree.sh
Removes startup script setup from the executor.
This functionality is now handled in the engine and script stores allow for sourcing startup repos from git based locations and s3 
Tested locally
=> refactor: remove startup script support

cli/createTemplate.sh
Include the contents of pre-assembled composite templates rather than relying on the `[#include]` directive to process their content.
As part of moving to dynamic input loading, reliance on pre-assembled templates needs to be removed. This change starts the process by using the `?interpret` builtin internally to avoid use of the `[#include]` directive.
=> refactor: composite template inclusion

cli/setup.sh
Align to the changes in the engine in regards to the loader parameter used to detect when the plugin state should be generated.
Part of fix for https://github.com/hamlet-io/engine/issues/1615
Local execution
=> fix: plugin refresh should ignore modules

cli/createTemplate.sh
- the pass alternative argument to the engine seems to have gone missing during recent changes. This puts  it back in
- Also adds debug log console output ( snuck along for the ride ) 
Generation of alternative templates was not behaving as it should
Tested locally
=> fix: command line options of pass alternative

cli/createTemplate.sh, execution/freemarker.sh
- Freemarker wrapper now relies on its environment to control where stdout and stderr go.
- "Generation successful" messages after each successful invocation of the freemarker engine are no longer logged.
Previously, the wrapper was always redirecting both stdout and stderr to the one target. With the changes to output handling in the wrapper and engine, the wrapper script now assumes the environment is set up to redirect output where required.
The logging of "generation successful" was removed to reduce the noise in the output generated during template creation.
=> fix: freemarker output redirection

cli/createTemplate.sh
Explicitly capture and analyse the status code returned by the freemarker engine. Also display any code that is not recognised.
It appears that for both arms of the if statement, the status code is set to 0 and not what the if expression provided.
Local template generations
=> fix: freemarker status code analysis

execution/setContext.sh
If using the CMDB plugin, bypass the generation of the blueprint. 
It was needed to inject the region information as command line options for the engine but this can now be sourced in the engine from the CMDB.
Local template generation both with and without the CMDB plugin.
- engine - https://github.com/hamlet-io/engine/pull/1667
- None
- None
=> fix: region in filenames

cli/manageCrypto.sh
Adds the key scope parameter which acts as fall back when the LOCATION can not be determined in set context. This allows for the manageCrypto command to run when you aren't in the CMDB segment or account dir and running commands using env vars for context. LOCATION is still preferred over the scope for backwards compatibility 
This allows for running manage crypto with the python executor when you aren't in the CMDB and instead have set a profile to control the context 
Tested locally
- None
- None
- None
=> feat: set key scope for out of repo crypto

execution/utility.sh
Adds a filter on contract steps to only execute the contract steps which are available and haven't already been completed
Since the engine can now execute steps in a contract before the executor sees the contract we need to filter out steps which have already been completed. 
Tested locally
- https://github.com/hamlet-io/engine/pull/1671
- None
- None
=> feat: filter contract steps based on status

cli/runExpoAppPublish.sh
Google Play only supports Id numbers up to 2100000000 so we just need to
make the date stamp shorter. Making it 9 numbers long to make sure we
don't hit this again
Mobile app versions 🙄 ...
Will be tested on local deployment
- None
- None
- None
=> fix(expo): reduce version code for android

execution/common.sh
Make the token used to detect use of the cmdb plugin more specific so directory names containing `cmdb` don't result in a false positive.
No surprises - don't trigger the dynamic cmdb behaviour unless it is really required.
- None
- None
- None
=> refactor: dynamic cmdb plugin detection

execution/utility.sh
Add function to set the inbound SES active ruleset.
This action can only be done via CLI. It is needed to integrate with the account level inbound SES support.
Local template generation.
- None
- Account inbound SES configuration - 
- None
=> feat: set SES active ruleset function

execution/setCredentials.sh
- Adds an authenticated call to aws as part of setCredential which returns the account the calling identity belongs to
- Use this return to both initialise authentication early and to also make sure the account matches the account that hamlet is trying to use
primary motivation is https://github.com/hamlet-io/executor-bash/issues/200 which raised an issue with deployments being triggered in wrong accounts if an MFA token is entered wrong or an aws config profile is missing
Tested locally
- None
- None
- None
=> feat: add check for aws account usage

cli/createTemplate.sh, execution/contextTree.sh, execution/freemarker.sh
Convert the .cmdb marker file to a directory to permit it to capture migration logs. The previous contents move to `config.json` within the directory.
Capture migration logs in the repo.
Local migration runs
- https://github.com/hamlet-io/executor-bash/pull/235
- None
- None
=> feat: .cmdb directory

cli/runExpoAppPublish.sh
Add expo app major version to the sentry source map URL.
The OTA URL has been updated to include the expo app major version. It requires Sentry source map URL passed to the sentry release job to be adjusted.
This minor change needs to be tested on the OSx box.  
- None
- None
- None
=> fix: correct SENTRY_SOURCE_MAP_S3_URL value

automation/jenkins/aws/manageBuildReferences.sh
fixes an issue where the format specific manage scripts were called and have now been removed
Accept release was failing on a missing registry management script 
Tested locally
- None
- None
- None
=> fix: registry handling for similar storage types

automation/jenkins/aws/manageImages.sh
- adds support for older variable names used when providing a docker image to manageImages. 
- adds prefix removal if the path to the dockerfile matches the context. This ensures the dockerfile is relative to the
context
Builds for existing pipelines were failing based on the new format
Tested locally
- None
- None
- None
=> fix: handle older env vars for docker images

automation/common.sh, automation/constructTree.sh, automation/jenkins/aws/setCredentials.sh, automation/setContext.sh, execution/setCredentials.sh
Adds support for the hamletcli as an automation provider. This allows for the automation scripts to provide support for using the cli as the script caller
Adds support for running the automation commands locally using the hamletcli provider: 
- Support for using an existing CMDB tree instead of constructing one. The ROOT_DIR must be defined along with the providing USE_EXISTING_TREE to the constructTree.sh script 
- Support for using user defined profiles when the automation scripts require AWS access
- Support for using the users global git config when commit changes to the repo
The motivation behind this change is to to allow the hamlet cli to manage the process of running our automation commands and centralises the …
=> feat: Hamletcli automation provider

automation/constructTree.sh
Fixes a typo in constructTree which was bypassing cloning
Causing builds to fail 
- None
- None
- None
=> fix: typo in existing tree check

automation/jenkins/aws/manageImages.sh
Removes a bug where the dockerfile was stripped based on context. Not required and breaks explicit path config
Causing builds to fail
- None
- None
- None
=> fix: remove stripping from context path for image

automation/jenkins/aws/manageBuildReferences.sh, automation/setContext.sh
Adds extra details to the log message when an invalid image format is provided.
Saves the registry types as a list in setContext so they can be used in the message
Make it easier to understand when things go wrong or are missing
- None
- None
- None
=> feat: extend logging for invalid image formats

automation/jenkins/aws/manageBuildReferences.sh
regression fix for handling image pulls from remote sources when using s3 registries
When trying to pull images from an S3 registry the script was running the verify operation when it should be pulling the image from the remote registry
Tested locally
- None
- None
- None
=> fix: use pull for remote image s3 pulls

execution/setCredentialsSource.sh
fixes an issue where the profile name was used instead of the account id when generating roles for switch profile
When using ENV, INSTANCE or USER auth configration the role wasn't generated properly and would fail to assume
Tested locally
- None
- None
- None
=> fix: aws role generation

execution/setCredentialsSource.sh
Minor fix to always make sure we have the save_context_property utility available 
In some cases the source configuration wasn't working 
Tested locally
- None
- None
- None
=> fix: credentials utility access

automation/jenkins/aws/manageDocker.sh
fixes an issue with the credentials used to check of an ecr repositoryexists in the registry
Pull jobs were failing with the wrong credentials
Tested locally
- None
- None
- None
=> fix(docker): ecr repository lookup credentials

automation/constructTree.sh, automation/setContext.sh, execution/utility.sh
Previously each invocation of `utility.sh` would empty the temporary file stack. With the adding of a call to `setCredentials.sh` (which sources `utility.sh`) in `createTemplate.sh` when running a script, the previously established temporary directory was lost resulting in the failure of subsequent template passes.
Along the way, a couple of other things were noted and fixed;
- the cmdb migration process was still being run by `constructTree.sh`
- the saving of registry types was happening BEFORE `AUTOMATION_DATA_DIR` was set, this variable being used by the `save_context_property` function used to save the registry types. As a result, the registry types were being saved to a temporary file which was then not accessible once …
=> fix: resetting of temporary file stack

automation/setContext.sh
Move the REGISTRY_TYPES to where they are first used within setContext
REGISTRY_PROVIDERS could not be found and auth wasn't working
Tested locally
- None
- None
- None
=> fix: registry type definitions location

cli/manageStack.sh
removes egrep usage in stack management status checks and use bash based regex instead
When running manageStack on an OSX based machine the following error is logged with the current regex used in status checks `egrep: repetition-operator operand invalid`
OSX appears to use a different grep build than whats in linux so the behaviour is different. 
now that the stackStatus variable is a string its possible to use the standard bash expression matching
Tested locally
- None
- None
- None
=> refactor: remove egrep usage for stack status

cli/createTemplate.sh
adds an extra file in the openapi definition search which is easier to follow when providing your own images
Makes it easier to integrate with build pipelines where the file name is defined by the user 
Tested locally
- None
- None
- None
=> feat: add simple api definition file name

cli/runExpoAppPublish.sh
- Adds support for using badge https://github.com/HazAT/badge to create environment labels on app icons before they are published. They are disabled by default and can be enabled with the -e parameter or by setting ENVIRONMENT_BADGE to true 
- Refactors some of the publish script to handle running the script locally from the hamlet cli 
Badges are to make it obvious to users who have two versions of the app for different environments installed on their phone. A key request for this was to distinguish between a training environment and a production one 
- None
- None
- None
=> feat: app icon badges

automation/common.sh, automation/jenkins/aws/manageRepo.sh, automation/jenkins/aws/saveCMDBRepos.sh, execution/common.sh
Adds support for deferring repository save events to a  later date instead of commit at the end of an action. 
- Adds support for staging changes made to a cmdb repository so that they can be saved as a batch
- Adds a check for a git repo and skips repository saving it the provided directory is not a repository
- Adds support for formatting multiple staged commit messages into a single commit message
- Adds a script to save all possible CMDBs as a batch. This will capture all of the changes that have been staged and save them under a standard message header
This allows you to perform a number of changes under a single task such as a full release and then save the changes at the end of the process. This also ensures that deploys …
=> feat: repository staged changes 

automation/constructTree.sh, automation/jenkins/aws/manageRepo.sh, automation/jenkins/aws/saveCMDBRepos.sh
- Handles locating the gen3 directories when an existing tree is used by constructTree
- fixes the creation of commit message if one cannot be found
- rely on constructTree to find the directories required for saving all cmdbs
- Include a check for account or product when saving CMDBS
Further testing revealed some issues in the save cmdb process which was caused by some issues in the handling of an existing CMDB for automation jobs
Tested locally
- None
- None
- None
=> fix: construct dirs and repo saving

execution/utility.sh
When providing the ssh-key as a string it needs to be base64 encoded or as a file. Using a file instead to align with what the aws examples have
works on aws cli v1 and v2 and allow for the key to be uplaoded
tested on deployment with issues
- None
- None
- None
=> fix(ssh): use a file when providing the key

automation/jenkins/aws/manageRepo.sh
- Adds a check that the commit stage file has content before filtering is applied
- uses content and file instead of just file exists for commit checking
When no staged changes were stored in the commit file an error was being logged by jq 
fixes: https://github.com/hamlet-io/engine/issues/1799
- None
- None
- None
=> fix: errors on saving repo state

automation/constructTree.sh, automation/jenkins/aws/saveCMDBRepos.sh, automation/setContext.sh, execution/setStackContext.sh
A collection of fixes and minor improvements around saving cmdb state 
- fixes determining the account using an existing CMDB tree in the automation context 
- Removes location checks in setStackContext as they are no longer required 
- Adds support for disabling Cloud provider credentials setup when its not required for automation 
- Fixes the use of the wrong directory when saving the cmdb state
A number of bugs found when testing the CMDB save state on a test pipeline 
- None
- None
- None
=> fix(automation): save cmdb config

cli/manageStack.sh
Ignore the exit status when submitting a change set
Was causing no op deployments to fail the overall run-deployment 
Tested locally
- None
- None
- None
=> fix: remove return from change set creation

execution/common.sh, execution/setCredentialsSource.sh
- Fixes a variable name in the fatal messages that was hiding the role that was attempted
- Skips searching for the root dir if it has already been defined
- Variable name makes it easier to follow what went wrong when running a command 
- Skipping the root dir search means that we don't need to create the root.json file if it has already been set
- None
- None
- None
=> fix: automation executor updates

execution/setCredentialsSource.sh
Only update the credentials profile for environment credentials when the source variables have content
When setCredentials was called during a task where it needed to switch accounts the env credentials were being wiped as we clear the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables in order to use profiles
- None
- None
- None
=> fix: env credential switching

.github/workflows/release.yml, README.md, cli/manageCrypto.sh, execution/manageJSON.sh
- Removes dos2unix from hamlet commands and instead relies on external management of file endings
- Updates readme to use the docs install guide 
- Fixes references to hamlet python package in cli
The dos2unix package is not installed in a lot of machines and adds an additional requirement to setting up hamlet. Its use has been limited and tools like git manage line endings anyway. Removing this from hamlet itself reduces the complexity in setting up hamlet
Tested locally
- None
- None
- None
=> refactor: remove dos2unix

execution/utility.sh
- Adds support for configuring each VPN Tunnel on a VPN connection individually
Makes it possible to configure different options for each tunnel
tested locally 
- None
- None
- None
=> feat: split vpn tunnel configuration

cli/manageStack.sh
- Adds a return on stack execution for delete actions
When a stack deletion failed the stack output files were being removed. They should be kept to ensure that the deployment is treated as still around 
- None
- None
- None
=> fix: handle failed stack deletes

automation/jenkins/aws/manageRepo.sh, automation/setContext.sh, cli/createTemplate.sh
- replaces dd with the bash RANDOM variable as dd behaves differently across operating systems and RANDOM is based on bash
- skips array lookups if the array is empty for deployment units
- uses the full definition of the iso8601 date format as osx date doesn't have the shorthand option
When running hamlet on macOS/OSX some of the commands different results or expect different arguments. This can lead to random error messages which usually are ignored by hamlet but can be confusing to people looking at the command output
Tested locally
- None
- None
- None
=> fix: macOS differences for commands

execution/utility.sh
Add function to set the retention for a log group.
For log groups created by AWS, it is still desirable to be able to set the retention desired, as the default is for log groups to never expire.
- None
- None
- None
=> feat: log group retention control

execution/utility.sh
- Adds a check for the log group before setting retention period
If the log group is not found the script will continue to allow for groups which are created on the first log event
- None
- None
- None
=> fix(cloudwatch): check for log group before retention update

automation/jenkins/aws/buildSetup.sh, automation/jenkins/aws/manageBuildReferences.sh, automation/jenkins/aws/manageImages.sh, automation/setContext.sh
- Adds support for providing JAR files as images for lambda functions
This adds a new build format lambda_jar which can be specified when uploading an image. The lambda function in the component will prefer the presence of the lambda jar over standard lambda zip functions
Allows for support of java based lambda functions in their native package format
tested locally using hamlet cli 
- None
- None
- None
=> feat(lambda): add support for lambda jar registry

cli/snapshotRDSDatabase.sh, execution/utility.sh
- Removes the time type from the sleep command
The sleep command in MacOS only supports providing a number and not the time type to sleep in ( i.e. it only supports seconds ) 
This also aligns the way we use sleep across the bash scripts
Tested locally
- None
- None
- None
=> fix: sleep command formatting for compatability

cli/createTemplate.sh
- change from using , to || to support providing JSON values via entrance parameters
The current comma separation for entrance parameters within the createTemplate script means that providing a JSON object as an entrance parameter causes createTemplate to split the JSON value which is then not processed by freemarker. Using a sperator like || means that it is unlikely to interfere with user provided inputs
- None
- None
- None
=> refactor: use weird seperate for user provided parameters

automation/setContext.sh
Ensure that the checking for a top level `build` directory doesn't depend on the working directory.
If the `dir()` step is being used, it may be convenient to not have to be in the top level workspace directory when calling `setContext.sh`.
Tricky to test - once merged I'll temporarily use the unicycle release in a customer site to confirm nothing breaks.
- None
- None
- None
=> fix(setContext) : AUTOMATION_BUILD_DIR

cli/createTemplate.sh, execution/setContext.sh
- Adds the ability to define the district used to assemble layers
Template generation failing for account level deployment units as the account location doesn't have the layers required to compile a segment district 
- None
- None
- None
=> feat: add support for providing the district cli option to templates

cli/createTemplate.sh, execution/setContext.sh
- Rename the DISTRICT env var/wrapper parameter to DISTRICT_TYPE
- Make all layer properties optional from the command line as they can be determined within the engine in some cases
- Move as many parameters as possible to optional to highlight usage and allow the engine to handle missing values effectively
- When using a CMDB context always set the DISTRICT_TYPE based on the LOCATION if its possible
This aligns with changes in the engine to separate the type of district from the future use of a district ID which would logically fit into the the DISTRICT environment variable. 
- None
- None
- None
=> refactor: district rename to district type

automation/constructTree.sh, cli/createTemplate.sh, execution/contextTree.sh
- Checks that ACCOUNT or PRODUCT are defined before search settings
- Filters paths for account and product dirs based on ACCOUNT and PRODUCT names
- removes tenant infrastrucutre dir
- removes wildcard filter for end and start composite fragments 
- When searching for settings directories with the product not set ( for ACCOUNT districts) the settings assembly process would search and assemble all products settings when it didn't need to. 
- Wildcard on composite fragment fixes - fixes https://github.com/hamlet-io/engine/issues/963 
tested locally
- None
- None
- None
=> refactor: scope settings search and remove legacy

automation/jenkins/aws/manageImages.sh
If an image path to a directory is provided when uploading images, first check if the directory already contains the required image.
If it does, use that, otherwise zip the directory.
This minimises the possibility of a double zip due to misconfiguration.
Difficult to test locally - will test with an affected customer config once merged.
- None
- None
- None
=> feat: detect existing images

automation/setContext.sh
Enhance the routine used to determine what level of property override should apply to handle three levels. While re-ordering
its parameters would make them more logical, add support for the extra level to the end to minimise the scope of the change.
Configure the account mapping logic to use this new capability.
Fixes https://github.com/hamlet-io/engine/issues/1992
Account mappings can have up to three levels of override - PRODUCT, ENVIRONMENT, SEGMENT. The current logic doesn't correctly support all combinations.
- manual testing of the `findAndDefineSetting` function
- testing (post merge) at customer site where issue has arisen
- None
- None
- None
=> fix: three level context properties

cli/createTemplate.sh
- Adds file path handling for the stackotput generated file
- Adds a stackoutput directory within the state dir to avoid generation overrides of the files
- Adds the ROOT_DIR as a parameter to the engine calls
Allows for the engine to generate it's own stack outputs as required
Tested locally
- None
- None
- None
=> feat: add stackoutput entrance support

cli/runExpoAppPublish.sh
- adds support for overriding the display name used for IOS mobile apps during deployment
This support issues with MDM solutions that require unique display names for apps that are being distributed
- None
- None
- None
=> feat(expo): add support for app display name on IOS apps

execution/setCredentialsSource.sh
Remove a redundant condition around the definition of `local_aws_auth_role`.
The conditional check uses what appears to be a mis-spelt variable name and hence is always treated as true.
Later code relies on `local_aws_auth_role` being defined so if the conditional ever returned false, later code would fail.
- None
- None
- None
=> refactor: set credentials

cli/manageCrypto.sh, execution/utility.sh
Handle AWS CLIv2's requirement for the additional parameter of `--cli-binary-format raw-in-base64-out` for the way we use kms encrypt
Caused a failure when upgrading Parks RDS
locally for `hamlet manage crypto`, but `hamlet deploy` doesn't seem to run the local "dev" executor utility.sh
- None
- None
- None
=> feat: support cliv2 kms encrypt

cli/runExpoAppPublish.sh
- Expo SDK 46 moved from a global cli to an embedded cli that is part of the standard expo packages. This removes the need to install it
- Removes the use of the public/asset url options that are no longer required
Align with the latest options available from expo
Will be tested in pipeline
- None
- None
- None
=> feat(expo): update cli usage for SDK 46+

cli/runExpoAppPublish.sh
- Adds the archive copy step for OTA's to ensure that source maps work for debugging with sentry
Was removed during cleanup as it didn't have much evidence of use, but then found it straight away.. 
Tested locally
- None
- None
- None
=> fix(expo): reinstate archive upload for sourcemaps

cli/runSentryRelease.sh
The prefix for react-native sentry integration has been changed to "app:///"
Source maps are not working for recently reported errors, 
locally
- None
- None
- None
=> fix: adjust sentry url prefix react-native apps

cli/runSentryRelease.sh
Fix the sed command syntax for correct sourceMappingURL replacement on MacOS
The correct value in sourceMappingURL is needed for the correct stacktrace frames to be shown in Sentry.
Locally
- None
- None
- None
=> fix: add an empty suffix for running on MacOS

cli/runSentryRelease.sh
Adds `-d` option to support --dist argument for sentry releases command
Sentry now requires distribution to be set along with the release during source maps upload for correct error processing.
Locally
- None
- None
- None
=> feat: add -d option for sentry distribution

execution/utility.sh
- Removes the ses password generation utility as is been removed from the AWS plugin
- Updates the BASH_SOURCE reference to align with it being an array
The SES password attribute was removed in https://github.com/hamlet-io/engine-plugin-aws/pull/669 and is no longer supported by most AWS SES API endpoints 
BASH_SOURCE builtin env var is an array value rather than a string
Tested locally
- https://github.com/hamlet-io/engine-plugin-aws/pull/669
- None
- None
=> refactor: ses password util and BASH_SOURCE

cli/runExpoAppPublish.sh
Set ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD=true for fastlane upload to TestFligh command
Mobile builds for iOS are failing due to regression in fastlane described [here ](https://github.com/fastlane/fastlane/issues/20756)
One of the proposed fixes has been applied and confirmed as working in CI.
CI MacOS Jenking agent
- None
- None
- None
=> fix: force ITMS package upload

.github/workflows/release.yml
Update the workflow version to pick up the fix to ensure the edge tag is added correctly to docker images.
Unicycle release was not picking up changes as `edge` tags were not being added to docker builds.
Difficult to test outside of github. Tested immediately following commit.
- None
- None
- None
=> fix: update release package version

cli/setup.sh
When querying whether a remote repo contains the desired reference, it is possible for more than one match to be returned. In this case, use the first match.
- avoid errors being thrown 
- ensure the plugin state if fully populated
Local testing
- None
- None
- None
=> fix(setup): handle multiple remote ref matches

cli/runExpoAppPublish.sh
Using this now seems to raise a new error with the latest version of xcode 
https://github.com/fastlane/fastlane/issues/20756
Publishing to iTunes Connect currently failing
- None
- None
- None
=> fix(expo): remove ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD override

cli/saveCMDBRepos.sh
Minor fix on cmdb save command which wasn't using -C for git push
the save cmdb command worked fine if you were in the repo dir but would break outside of it
Tested locally
- None
- None
- None
=> fix: set dir for git push

execution/utility.sh
Adds support for checking a db cluster as well as a standard db instance when restoring from snapshots in RDS
Deployment currently fails when restoring a cluster snapshot
- None
- None
- None
=> feat(db): add support for checking cluster username
